on:
  push: 
    # TODO: Change after testing
    branches:
      - ci/build-release
jobs:
  build_release:
    runs-on: ubuntu-latest
    name: Build
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: linux
            arch: 386
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
          - os: windows
            arch: amd64
          - os: windows
            arch: arm64
          - os: windows 
            arch: 386
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - run: mkdir out && cp -r templates out/templates
      - name: Build
        run: cd src && go build -o ../out . 
        env:
          GOARCH: ${{ matrix.arch }}
          GOOS: ${{ matrix.os }}
      - name: Create tar
        run: cd out && tar cvf ../donggu-${{ matrix.os }}-${{ matrix.arch }}.tar *
      - name: Upload artifact 
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}-${{ matrix.arch }}
          path: donggu-${{ matrix.os }}-${{ matrix.arch }}.tar